#cloud-config

package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3
  - python3-venv
  - build-essential

# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /tmp/setup-simulated-digital-twin.sh
    permissions: "0755"
    content: |
      cd /home/ubuntu
      git clone https://github.com/gtfierro/simulated-digital-twin
      cd simulated-digital-twin && bash setup.sh


# create the docker group
groups:
  - docker

# Install Docker, for production, consider pinning to stable versionsruncmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
  - systemctl start docker
  - systemctl enable docker
  - chmod +x /tmp/setup-simulated-digital-twin.sh
  - bash /tmp/setup-simulated-digital-twin.sh

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]
